#!/usr/bin/env bash
#
# DM-14 — Render infra/tenants/demo.tfvars from the landing-zone outputs.
#
# Reads `terraform output -json` of demo/landing-zone (run after a successful
# apply, so the MG/subscription IDs are real) and writes the scope variables
# into infra/tenants/demo.tfvars for use with ./infra/deploy.sh demo.
#
# Usage (from repo root or anywhere):
#   demo/landing-zone/render-demo-tfvars.sh \
#     [--alert-email you@example.com] [--out infra/tenants/demo.tfvars]
#
# Requires: terraform, jq. Run after `terraform -chdir=demo/landing-zone apply`.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LZ_DIR="$SCRIPT_DIR"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUT="$REPO_ROOT/infra/tenants/demo.tfvars"
ALERT_EMAIL="<your-demo-alert-email>"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --alert-email) ALERT_EMAIL="$2"; shift 2 ;;
    --out)         OUT="$2"; shift 2 ;;
    -h|--help)     sed -n '2,15p' "$0"; exit 0 ;;
    *)             echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

command -v jq >/dev/null || { echo "jq is required" >&2; exit 1; }

echo "Reading landing-zone outputs from $LZ_DIR ..."
OUTPUTS_JSON="$(terraform -chdir="$LZ_DIR" output -json)"

get() { jq -r "$1" <<<"$OUTPUTS_JSON"; }

MGMT_SUB="$(get '.subscription_ids.value.management')"
ROLE_SCOPE="$(get '.role_assignable_scope.value')"

# Build HCL list literals from the JSON arrays.
in_scope_hcl="$(get '.in_scope_management_group_ids.value[]' | sed 's/^/  "/; s/$/",/')"
excluded_hcl="$(get '.excluded_scope_ids.value[]'          | sed 's/^/  "/; s/$/",/')"

mkdir -p "$(dirname "$OUT")"

cat > "$OUT" <<EOF
# AUTO-GENERATED by demo/landing-zone/render-demo-tfvars.sh (DM-14).
# Values come from the landing-zone outputs. Edit the alert email / toggles as
# needed. This file is gitignored (*.tfvars).

subscription_id = "$MGMT_SUB"
location        = "southeastasia"

name_suffix = ""

role_assignable_scope = "$ROLE_SCOPE"

in_scope_management_group_ids = [
$in_scope_hcl
]

excluded_scope_ids = [
$excluded_hcl
]

enabled_resource_types = ["vm", "vmss", "aks", "postgres-flex", "mysql-flex", "sqlmi", "appgw"]

reconcile_schedule  = "0 */15 * * * *"
dry_run             = true
max_actions_per_run = 200

log_analytics_workspace_id = ""
alert_email_addresses      = ["$ALERT_EMAIL"]

enable_private_networking = false

tags = {
  owner       = "demo"
  cost-centre = "demo"
  project     = "power-scheduler-demo"
  managed-by  = "terraform"
}
EOF

echo "Wrote $OUT"
echo "Review it, then deploy with the per-tenant wrapper (safe backend handling):"
echo "  ./infra/deploy.sh demo plan"
echo "  ./infra/deploy.sh demo apply"
echo "(Ensure infra/tenants/demo.backend.hcl exists — copy demo.backend.hcl.example.)"
